CREATE TABLE IF NOT EXISTS content (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type ENUM('review', 'article') NOT NULL,
  title VARCHAR(255) NOT NULL,
  author_name VARCHAR(120) NOT NULL DEFAULT 'Gaming With The Bard',
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  image_url TEXT NULL,
  video_url TEXT NULL,
  genres_json JSON NOT NULL,
  platforms_json JSON NOT NULL,
  screenshots_json JSON NOT NULL,
  related_games_json JSON NOT NULL,
  bard_score NUMERIC(4,2),
  build_quality NUMERIC(4,2),
  respects_time VARCHAR(100) NULL,
  steam_deck TINYINT(1) NOT NULL DEFAULT 0,
  steam_deck_fps VARCHAR(120) NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'published',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  published_at DATETIME NULL,
  INDEX idx_content_type (type),
  INDEX idx_content_status (status),
  INDEX idx_content_created_at (created_at)
);
